baseURL = "https://aurea-li.github.io/"
languageCode = "en-us"
title = "Sheep Garden"
theme = "PaperMod"

[taxonomies]

[params]
  defaultTheme = "light"
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowToc = false
  mainSections = ["posts"]
  disableSpecial1stPost = true
  hideSummary = true
  hideFooter = true

[params.imageStore]
  baseURL = "https://raw.githubusercontent.com/Aurea-Li/image-store-2026/main/"
  displayDir = "display"
  originalDir = ""
  manifestURL = "https://raw.githubusercontent.com/Aurea-Li/image-store-2026/main/display/manifest.json"

[params.homeInfoParams]
  Title = ""
  Content = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'
