baseURL = "https://aurea-li.github.io/"
languageCode = "en-us"
title = "Digital Garden"
theme = "PaperMod"

[taxonomies]

[params]
  defaultTheme = "light"
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowToc = false
  mainSections = ["posts"]
  disableSpecial1stPost = true
  hideSummary = true
  hideFooter = true

[params.homeInfoParams]
  Title = ""
  Content = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'
